# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance <- function(start, end) {
    .Call('_cRacle_distance', PACKAGE = 'cRacle', start, end)
}

findcoord <- function(lon, lat, dist, brng) {
    .Call('_cRacle_findcoord', PACKAGE = 'cRacle', lon, lat, dist, brng)
}

latlonfromcell <- function(cells, extent, nrow, ncol) {
    .Call('_cRacle_latlonfromcell', PACKAGE = 'cRacle', cells, extent, nrow, ncol)
}

pythagorean <- function(start, end) {
    .Call('_cRacle_pythagorean', PACKAGE = 'cRacle', start, end)
}

